### PR TITLE
[#128][bugfix]Mobile Page Cutoff Fix

### PR DESCRIPTION
**Pull request by c0rnkrump3t**

### CODE REVIEW

**Review by EyalAzimov — APPROVED** [review]
Thanks!

**Review by kikkiii21 — CHANGES_REQUESTED** [review]
Looks good, 
could you please follow the format for the title of the PR, 
could you assign the issue it relates too,
and could you center this button 
Screenshot 2023-02-15 at 2 24 29 PM

**Review by kikkiii21 — APPROVED** [review]
It would be great if all the info could fit in one page and we didn't have the need to scroll down to use the update button, but thank you for implementing the requested change

**Comment by c0rnkrump3t** [comment]
Ok no prob I'll make sure everything is on the page and no scrolling needed

**Pull request merged**
