### PR TITLE
Sp 21 camera based event creation 2

### LINKED ISSUE #102: Camera-based Event Creation 2 [SP-21]
This issue follows up #21 by doing basic formatting on the text obtained from the image and sending back a json dictionary of the relevant fields (event name, event description, event date, event time, etc). This json dictionary should be used to populate an 'Add Event' drawer (shown below), allowing the user to either confirm or edit the fields as required before confirming the event addition.
Screen Shot 2023-01-18 at 2 56 07 PM

Frontend:
- [ ] Use the add image drawer to get the text (as a json object) from an image
- [ ] Close the image drawer and open an 'Add Event' drawer
- [ ] Populate the 'Add Event' drawer with the information in the json object

Backend:
- [ ] Categorize the text obtained from the request image into event name, event description, event date, event time, etc. as needed
- [ ] Create a json dictionary based on the categories (keys) determined above
- [ ] Send the json dictionary as a response to the request

### PR DESCRIPTION
**Pull request by mnashat**
This PR implements event creation using an uploaded image.

Closes #102 

Test images used are shown below:
test image 2
test image 3
test image 4
test image
TMP_RichTextLineIndent

### CODE REVIEW

**Review by guaj — APPROVED** [review]

**Comment by guaj** [comment]
Try to not refactor spaces, it make the code reviewer heavier for nothing...

**Comment by mnashat** [comment]
> Try to not refactor spaces, it make the code review heavier for nothing...

You're right. Sorry about that.

**Review by kikkiii21 — COMMENTED** [review]
The add event drawer does not have the categories and when an event is created, it should be categorized. Also, when I click on 'add' I think we should be redirected to the homepage instead of the upload an image page?

**Comment by mnashat** [comment]
> The add event drawer does not have the categories and when an event is created, it should be categorized. Also, when I click on 'add' I think we should be redirected to the homepage instead of the upload an image page?

With respect to the categories, their PR was just merged into main, hence why my branch does not include the categories in the add event drawer.

With respect to redirecting, it is possible to close both drawers. However, given the way they currently behave, they have to be closed one after the other, which doesn't look the best in my opinion. Moreover, since the user cannot add multiple events using just one image, I thought it would make sense for the image drawer to stay open for the user to add another image if they liked. Let me know what you think regarding this. I can quickly reimplement closing both drawers if that ends up making more sense.

**Comment by kikkiii21** [comment]
> > The add event drawer does not have the categories and when an event is created, it should be categorized. Also, when I click on 'add' I think we should be redirected to the homepage instead of the upload an image page?
> 
> With respect to the categories, their PR was just merged into main, hence why my branch does not include the categories in the add event drawer.
> 
> With respect to redirecting, it is possible to close both drawers. However, given the way they currently behave, they have to be closed one after the other, which doesn't look the best in my opinion. Moreover, since the user cannot add multiple events using just one image, I thought it would make sense for the image drawer to stay open for the user to add another image if they liked. Let me know what you think regarding this. I can quickly reimplement closing both drawers if that ends up making more sense.

I personally prefer being redirected to the calendar homepage after creating a new event, but it would look weird to see 2 drawers close before going to the calendar view page, therefore I think it's best to leave as is.

**Review by kikkiii21 — APPROVED** [review]
Thank you for updating the branch! Works great

**Pull request merged**
